//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 12:59:43 PM CDT 
//


package edu.utdallas.hltri.data.clinical_trials.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for analysis_struct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="analysis_struct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="group_id_list">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="group_id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="groups_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="non_inferiority_type" type="{}non_inferiority_type_enum" minOccurs="0"/>
 *         &lt;element name="non_inferiority_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="p_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="p_value_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="method_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="param_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="param_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dispersion_type" type="{}analysis_dispersion_enum" minOccurs="0"/>
 *         &lt;element name="dispersion_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ci_percent" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ci_n_sides" type="{}n_sides_enum" minOccurs="0"/>
 *         &lt;element name="ci_lower_limit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ci_upper_limit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ci_upper_limit_na_comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estimate_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="other_analysis_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "analysis_struct", propOrder = {
    "groupIdList",
    "groupsDesc",
    "nonInferiorityType",
    "nonInferiorityDesc",
    "pValue",
    "pValueDesc",
    "method",
    "methodDesc",
    "paramType",
    "paramValue",
    "dispersionType",
    "dispersionValue",
    "ciPercent",
    "ciNSides",
    "ciLowerLimit",
    "ciUpperLimit",
    "ciUpperLimitNaComment",
    "estimateDesc",
    "otherAnalysisDesc"
})
public class AnalysisStruct
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "group_id_list", required = true)
    protected AnalysisStruct.GroupIdList groupIdList;
    @XmlElement(name = "groups_desc")
    protected String groupsDesc;
    @XmlElement(name = "non_inferiority_type")
    @XmlSchemaType(name = "string")
    protected NonInferiorityTypeEnum nonInferiorityType;
    @XmlElement(name = "non_inferiority_desc")
    protected String nonInferiorityDesc;
    @XmlElement(name = "p_value")
    protected String pValue;
    @XmlElement(name = "p_value_desc")
    protected String pValueDesc;
    protected String method;
    @XmlElement(name = "method_desc")
    protected String methodDesc;
    @XmlElement(name = "param_type")
    protected String paramType;
    @XmlElement(name = "param_value")
    protected String paramValue;
    @XmlElement(name = "dispersion_type")
    @XmlSchemaType(name = "string")
    protected AnalysisDispersionEnum dispersionType;
    @XmlElement(name = "dispersion_value")
    protected String dispersionValue;
    @XmlElement(name = "ci_percent")
    protected Float ciPercent;
    @XmlElement(name = "ci_n_sides")
    protected String ciNSides;
    @XmlElement(name = "ci_lower_limit")
    protected String ciLowerLimit;
    @XmlElement(name = "ci_upper_limit")
    protected String ciUpperLimit;
    @XmlElement(name = "ci_upper_limit_na_comment")
    protected String ciUpperLimitNaComment;
    @XmlElement(name = "estimate_desc")
    protected String estimateDesc;
    @XmlElement(name = "other_analysis_desc")
    protected String otherAnalysisDesc;

    /**
     * Gets the value of the groupIdList property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisStruct.GroupIdList }
     *     
     */
    public AnalysisStruct.GroupIdList getGroupIdList() {
        return groupIdList;
    }

    /**
     * Sets the value of the groupIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisStruct.GroupIdList }
     *     
     */
    public void setGroupIdList(AnalysisStruct.GroupIdList value) {
        this.groupIdList = value;
    }

    /**
     * Gets the value of the groupsDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupsDesc() {
        return groupsDesc;
    }

    /**
     * Sets the value of the groupsDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupsDesc(String value) {
        this.groupsDesc = value;
    }

    /**
     * Gets the value of the nonInferiorityType property.
     * 
     * @return
     *     possible object is
     *     {@link NonInferiorityTypeEnum }
     *     
     */
    public NonInferiorityTypeEnum getNonInferiorityType() {
        return nonInferiorityType;
    }

    /**
     * Sets the value of the nonInferiorityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonInferiorityTypeEnum }
     *     
     */
    public void setNonInferiorityType(NonInferiorityTypeEnum value) {
        this.nonInferiorityType = value;
    }

    /**
     * Gets the value of the nonInferiorityDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonInferiorityDesc() {
        return nonInferiorityDesc;
    }

    /**
     * Sets the value of the nonInferiorityDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonInferiorityDesc(String value) {
        this.nonInferiorityDesc = value;
    }

    /**
     * Gets the value of the pValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPValue() {
        return pValue;
    }

    /**
     * Sets the value of the pValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPValue(String value) {
        this.pValue = value;
    }

    /**
     * Gets the value of the pValueDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPValueDesc() {
        return pValueDesc;
    }

    /**
     * Sets the value of the pValueDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPValueDesc(String value) {
        this.pValueDesc = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the methodDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodDesc() {
        return methodDesc;
    }

    /**
     * Sets the value of the methodDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodDesc(String value) {
        this.methodDesc = value;
    }

    /**
     * Gets the value of the paramType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * Sets the value of the paramType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamType(String value) {
        this.paramType = value;
    }

    /**
     * Gets the value of the paramValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * Sets the value of the paramValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamValue(String value) {
        this.paramValue = value;
    }

    /**
     * Gets the value of the dispersionType property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisDispersionEnum }
     *     
     */
    public AnalysisDispersionEnum getDispersionType() {
        return dispersionType;
    }

    /**
     * Sets the value of the dispersionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisDispersionEnum }
     *     
     */
    public void setDispersionType(AnalysisDispersionEnum value) {
        this.dispersionType = value;
    }

    /**
     * Gets the value of the dispersionValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispersionValue() {
        return dispersionValue;
    }

    /**
     * Sets the value of the dispersionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispersionValue(String value) {
        this.dispersionValue = value;
    }

    /**
     * Gets the value of the ciPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCiPercent() {
        return ciPercent;
    }

    /**
     * Sets the value of the ciPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCiPercent(Float value) {
        this.ciPercent = value;
    }

    /**
     * Gets the value of the ciNSides property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiNSides() {
        return ciNSides;
    }

    /**
     * Sets the value of the ciNSides property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiNSides(String value) {
        this.ciNSides = value;
    }

    /**
     * Gets the value of the ciLowerLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiLowerLimit() {
        return ciLowerLimit;
    }

    /**
     * Sets the value of the ciLowerLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiLowerLimit(String value) {
        this.ciLowerLimit = value;
    }

    /**
     * Gets the value of the ciUpperLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiUpperLimit() {
        return ciUpperLimit;
    }

    /**
     * Sets the value of the ciUpperLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiUpperLimit(String value) {
        this.ciUpperLimit = value;
    }

    /**
     * Gets the value of the ciUpperLimitNaComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiUpperLimitNaComment() {
        return ciUpperLimitNaComment;
    }

    /**
     * Sets the value of the ciUpperLimitNaComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiUpperLimitNaComment(String value) {
        this.ciUpperLimitNaComment = value;
    }

    /**
     * Gets the value of the estimateDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstimateDesc() {
        return estimateDesc;
    }

    /**
     * Sets the value of the estimateDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstimateDesc(String value) {
        this.estimateDesc = value;
    }

    /**
     * Gets the value of the otherAnalysisDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherAnalysisDesc() {
        return otherAnalysisDesc;
    }

    /**
     * Sets the value of the otherAnalysisDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherAnalysisDesc(String value) {
        this.otherAnalysisDesc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="group_id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groupId"
    })
    public static class GroupIdList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "group_id", required = true)
        protected List<String> groupId;

        /**
         * Gets the value of the groupId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the groupId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGroupId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getGroupId() {
            if (groupId == null) {
                groupId = new ArrayList<String>();
            }
            return this.groupId;
        }

    }

}
