//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 12:59:43 PM CDT 
//


package edu.utdallas.hltri.data.clinical_trials.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expanded_access_status_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="expanded_access_status_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Available"/>
 *     &lt;enumeration value="No longer available"/>
 *     &lt;enumeration value="Temporarily not available"/>
 *     &lt;enumeration value="Approved for marketing"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "expanded_access_status_enum")
@XmlEnum
public enum ExpandedAccessStatusEnum {

    @XmlEnumValue("Available")
    AVAILABLE("Available"),
    @XmlEnumValue("No longer available")
    NO_LONGER_AVAILABLE("No longer available"),
    @XmlEnumValue("Temporarily not available")
    TEMPORARILY_NOT_AVAILABLE("Temporarily not available"),
    @XmlEnumValue("Approved for marketing")
    APPROVED_FOR_MARKETING("Approved for marketing");
    private final String value;

    ExpandedAccessStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExpandedAccessStatusEnum fromValue(String v) {
        for (ExpandedAccessStatusEnum c: ExpandedAccessStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
