//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 12:59:43 PM CDT 
//


package edu.utdallas.hltri.data.clinical_trials.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.utdallas.hltri.data.clinical_trials.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.utdallas.hltri.data.clinical_trials.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParticipantFlowStruct }
     * 
     */
    public ParticipantFlowStruct createParticipantFlowStruct() {
        return new ParticipantFlowStruct();
    }

    /**
     * Create an instance of {@link EventsStruct }
     * 
     */
    public EventsStruct createEventsStruct() {
        return new EventsStruct();
    }

    /**
     * Create an instance of {@link MeasureClassStruct }
     * 
     */
    public MeasureClassStruct createMeasureClassStruct() {
        return new MeasureClassStruct();
    }

    /**
     * Create an instance of {@link PeriodStruct }
     * 
     */
    public PeriodStruct createPeriodStruct() {
        return new PeriodStruct();
    }

    /**
     * Create an instance of {@link ResultsOutcomeStruct }
     * 
     */
    public ResultsOutcomeStruct createResultsOutcomeStruct() {
        return new ResultsOutcomeStruct();
    }

    /**
     * Create an instance of {@link EventCategoryStruct }
     * 
     */
    public EventCategoryStruct createEventCategoryStruct() {
        return new EventCategoryStruct();
    }

    /**
     * Create an instance of {@link MeasureCategoryStruct }
     * 
     */
    public MeasureCategoryStruct createMeasureCategoryStruct() {
        return new MeasureCategoryStruct();
    }

    /**
     * Create an instance of {@link MeasureAnalyzedStruct }
     * 
     */
    public MeasureAnalyzedStruct createMeasureAnalyzedStruct() {
        return new MeasureAnalyzedStruct();
    }

    /**
     * Create an instance of {@link MilestoneStruct }
     * 
     */
    public MilestoneStruct createMilestoneStruct() {
        return new MilestoneStruct();
    }

    /**
     * Create an instance of {@link BaselineStruct }
     * 
     */
    public BaselineStruct createBaselineStruct() {
        return new BaselineStruct();
    }

    /**
     * Create an instance of {@link ReportedEventsStruct }
     * 
     */
    public ReportedEventsStruct createReportedEventsStruct() {
        return new ReportedEventsStruct();
    }

    /**
     * Create an instance of {@link MeasureStruct }
     * 
     */
    public MeasureStruct createMeasureStruct() {
        return new MeasureStruct();
    }

    /**
     * Create an instance of {@link AnalysisStruct }
     * 
     */
    public AnalysisStruct createAnalysisStruct() {
        return new AnalysisStruct();
    }

    /**
     * Create an instance of {@link ClinicalResultsStruct }
     * 
     */
    public ClinicalResultsStruct createClinicalResultsStruct() {
        return new ClinicalResultsStruct();
    }

    /**
     * Create an instance of {@link ClinicalStudy }
     * 
     */
    public ClinicalStudy createClinicalStudy() {
        return new ClinicalStudy();
    }

    /**
     * Create an instance of {@link RequiredHeaderStruct }
     * 
     */
    public RequiredHeaderStruct createRequiredHeaderStruct() {
        return new RequiredHeaderStruct();
    }

    /**
     * Create an instance of {@link IdInfoStruct }
     * 
     */
    public IdInfoStruct createIdInfoStruct() {
        return new IdInfoStruct();
    }

    /**
     * Create an instance of {@link SponsorsStruct }
     * 
     */
    public SponsorsStruct createSponsorsStruct() {
        return new SponsorsStruct();
    }

    /**
     * Create an instance of {@link OversightInfoStruct }
     * 
     */
    public OversightInfoStruct createOversightInfoStruct() {
        return new OversightInfoStruct();
    }

    /**
     * Create an instance of {@link TextblockStruct }
     * 
     */
    public TextblockStruct createTextblockStruct() {
        return new TextblockStruct();
    }

    /**
     * Create an instance of {@link VariableDateStruct }
     * 
     */
    public VariableDateStruct createVariableDateStruct() {
        return new VariableDateStruct();
    }

    /**
     * Create an instance of {@link ExpandedAccessInfoStruct }
     * 
     */
    public ExpandedAccessInfoStruct createExpandedAccessInfoStruct() {
        return new ExpandedAccessInfoStruct();
    }

    /**
     * Create an instance of {@link StudyDesignInfoStruct }
     * 
     */
    public StudyDesignInfoStruct createStudyDesignInfoStruct() {
        return new StudyDesignInfoStruct();
    }

    /**
     * Create an instance of {@link ProtocolOutcomeStruct }
     * 
     */
    public ProtocolOutcomeStruct createProtocolOutcomeStruct() {
        return new ProtocolOutcomeStruct();
    }

    /**
     * Create an instance of {@link EnrollmentStruct }
     * 
     */
    public EnrollmentStruct createEnrollmentStruct() {
        return new EnrollmentStruct();
    }

    /**
     * Create an instance of {@link ArmGroupStruct }
     * 
     */
    public ArmGroupStruct createArmGroupStruct() {
        return new ArmGroupStruct();
    }

    /**
     * Create an instance of {@link InterventionStruct }
     * 
     */
    public InterventionStruct createInterventionStruct() {
        return new InterventionStruct();
    }

    /**
     * Create an instance of {@link EligibilityStruct }
     * 
     */
    public EligibilityStruct createEligibilityStruct() {
        return new EligibilityStruct();
    }

    /**
     * Create an instance of {@link InvestigatorStruct }
     * 
     */
    public InvestigatorStruct createInvestigatorStruct() {
        return new InvestigatorStruct();
    }

    /**
     * Create an instance of {@link ContactStruct }
     * 
     */
    public ContactStruct createContactStruct() {
        return new ContactStruct();
    }

    /**
     * Create an instance of {@link LocationStruct }
     * 
     */
    public LocationStruct createLocationStruct() {
        return new LocationStruct();
    }

    /**
     * Create an instance of {@link CountriesStruct }
     * 
     */
    public CountriesStruct createCountriesStruct() {
        return new CountriesStruct();
    }

    /**
     * Create an instance of {@link LinkStruct }
     * 
     */
    public LinkStruct createLinkStruct() {
        return new LinkStruct();
    }

    /**
     * Create an instance of {@link ReferenceStruct }
     * 
     */
    public ReferenceStruct createReferenceStruct() {
        return new ReferenceStruct();
    }

    /**
     * Create an instance of {@link ResponsiblePartyStruct }
     * 
     */
    public ResponsiblePartyStruct createResponsiblePartyStruct() {
        return new ResponsiblePartyStruct();
    }

    /**
     * Create an instance of {@link BrowseStruct }
     * 
     */
    public BrowseStruct createBrowseStruct() {
        return new BrowseStruct();
    }

    /**
     * Create an instance of {@link PatientDataStruct }
     * 
     */
    public PatientDataStruct createPatientDataStruct() {
        return new PatientDataStruct();
    }

    /**
     * Create an instance of {@link StudyDocsStruct }
     * 
     */
    public StudyDocsStruct createStudyDocsStruct() {
        return new StudyDocsStruct();
    }

    /**
     * Create an instance of {@link VocabTermStruct }
     * 
     */
    public VocabTermStruct createVocabTermStruct() {
        return new VocabTermStruct();
    }

    /**
     * Create an instance of {@link AddressStruct }
     * 
     */
    public AddressStruct createAddressStruct() {
        return new AddressStruct();
    }

    /**
     * Create an instance of {@link MeasureCountStruct }
     * 
     */
    public MeasureCountStruct createMeasureCountStruct() {
        return new MeasureCountStruct();
    }

    /**
     * Create an instance of {@link GroupStruct }
     * 
     */
    public GroupStruct createGroupStruct() {
        return new GroupStruct();
    }

    /**
     * Create an instance of {@link EventStruct }
     * 
     */
    public EventStruct createEventStruct() {
        return new EventStruct();
    }

    /**
     * Create an instance of {@link CertainAgreementsStruct }
     * 
     */
    public CertainAgreementsStruct createCertainAgreementsStruct() {
        return new CertainAgreementsStruct();
    }

    /**
     * Create an instance of {@link ParticipantsStruct }
     * 
     */
    public ParticipantsStruct createParticipantsStruct() {
        return new ParticipantsStruct();
    }

    /**
     * Create an instance of {@link FacilityStruct }
     * 
     */
    public FacilityStruct createFacilityStruct() {
        return new FacilityStruct();
    }

    /**
     * Create an instance of {@link EventCountsStruct }
     * 
     */
    public EventCountsStruct createEventCountsStruct() {
        return new EventCountsStruct();
    }

    /**
     * Create an instance of {@link MeasurementStruct }
     * 
     */
    public MeasurementStruct createMeasurementStruct() {
        return new MeasurementStruct();
    }

    /**
     * Create an instance of {@link SponsorStruct }
     * 
     */
    public SponsorStruct createSponsorStruct() {
        return new SponsorStruct();
    }

    /**
     * Create an instance of {@link PointOfContactStruct }
     * 
     */
    public PointOfContactStruct createPointOfContactStruct() {
        return new PointOfContactStruct();
    }

    /**
     * Create an instance of {@link StudyDocStruct }
     * 
     */
    public StudyDocStruct createStudyDocStruct() {
        return new StudyDocStruct();
    }

    /**
     * Create an instance of {@link ParticipantFlowStruct.GroupList }
     * 
     */
    public ParticipantFlowStruct.GroupList createParticipantFlowStructGroupList() {
        return new ParticipantFlowStruct.GroupList();
    }

    /**
     * Create an instance of {@link ParticipantFlowStruct.PeriodList }
     * 
     */
    public ParticipantFlowStruct.PeriodList createParticipantFlowStructPeriodList() {
        return new ParticipantFlowStruct.PeriodList();
    }

    /**
     * Create an instance of {@link EventsStruct.CategoryList }
     * 
     */
    public EventsStruct.CategoryList createEventsStructCategoryList() {
        return new EventsStruct.CategoryList();
    }

    /**
     * Create an instance of {@link MeasureClassStruct.AnalyzedList }
     * 
     */
    public MeasureClassStruct.AnalyzedList createMeasureClassStructAnalyzedList() {
        return new MeasureClassStruct.AnalyzedList();
    }

    /**
     * Create an instance of {@link MeasureClassStruct.CategoryList }
     * 
     */
    public MeasureClassStruct.CategoryList createMeasureClassStructCategoryList() {
        return new MeasureClassStruct.CategoryList();
    }

    /**
     * Create an instance of {@link PeriodStruct.MilestoneList }
     * 
     */
    public PeriodStruct.MilestoneList createPeriodStructMilestoneList() {
        return new PeriodStruct.MilestoneList();
    }

    /**
     * Create an instance of {@link PeriodStruct.DropWithdrawReasonList }
     * 
     */
    public PeriodStruct.DropWithdrawReasonList createPeriodStructDropWithdrawReasonList() {
        return new PeriodStruct.DropWithdrawReasonList();
    }

    /**
     * Create an instance of {@link ResultsOutcomeStruct.GroupList }
     * 
     */
    public ResultsOutcomeStruct.GroupList createResultsOutcomeStructGroupList() {
        return new ResultsOutcomeStruct.GroupList();
    }

    /**
     * Create an instance of {@link ResultsOutcomeStruct.AnalysisList }
     * 
     */
    public ResultsOutcomeStruct.AnalysisList createResultsOutcomeStructAnalysisList() {
        return new ResultsOutcomeStruct.AnalysisList();
    }

    /**
     * Create an instance of {@link EventCategoryStruct.EventList }
     * 
     */
    public EventCategoryStruct.EventList createEventCategoryStructEventList() {
        return new EventCategoryStruct.EventList();
    }

    /**
     * Create an instance of {@link MeasureCategoryStruct.MeasurementList }
     * 
     */
    public MeasureCategoryStruct.MeasurementList createMeasureCategoryStructMeasurementList() {
        return new MeasureCategoryStruct.MeasurementList();
    }

    /**
     * Create an instance of {@link MeasureAnalyzedStruct.CountList }
     * 
     */
    public MeasureAnalyzedStruct.CountList createMeasureAnalyzedStructCountList() {
        return new MeasureAnalyzedStruct.CountList();
    }

    /**
     * Create an instance of {@link MilestoneStruct.ParticipantsList }
     * 
     */
    public MilestoneStruct.ParticipantsList createMilestoneStructParticipantsList() {
        return new MilestoneStruct.ParticipantsList();
    }

    /**
     * Create an instance of {@link BaselineStruct.GroupList }
     * 
     */
    public BaselineStruct.GroupList createBaselineStructGroupList() {
        return new BaselineStruct.GroupList();
    }

    /**
     * Create an instance of {@link BaselineStruct.AnalyzedList }
     * 
     */
    public BaselineStruct.AnalyzedList createBaselineStructAnalyzedList() {
        return new BaselineStruct.AnalyzedList();
    }

    /**
     * Create an instance of {@link BaselineStruct.MeasureList }
     * 
     */
    public BaselineStruct.MeasureList createBaselineStructMeasureList() {
        return new BaselineStruct.MeasureList();
    }

    /**
     * Create an instance of {@link ReportedEventsStruct.GroupList }
     * 
     */
    public ReportedEventsStruct.GroupList createReportedEventsStructGroupList() {
        return new ReportedEventsStruct.GroupList();
    }

    /**
     * Create an instance of {@link MeasureStruct.AnalyzedList }
     * 
     */
    public MeasureStruct.AnalyzedList createMeasureStructAnalyzedList() {
        return new MeasureStruct.AnalyzedList();
    }

    /**
     * Create an instance of {@link MeasureStruct.ClassList }
     * 
     */
    public MeasureStruct.ClassList createMeasureStructClassList() {
        return new MeasureStruct.ClassList();
    }

    /**
     * Create an instance of {@link AnalysisStruct.GroupIdList }
     * 
     */
    public AnalysisStruct.GroupIdList createAnalysisStructGroupIdList() {
        return new AnalysisStruct.GroupIdList();
    }

    /**
     * Create an instance of {@link ClinicalResultsStruct.OutcomeList }
     * 
     */
    public ClinicalResultsStruct.OutcomeList createClinicalResultsStructOutcomeList() {
        return new ClinicalResultsStruct.OutcomeList();
    }

}
