//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 12:59:43 PM CDT 
//


package edu.utdallas.hltri.data.clinical_trials.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oversight_info_struct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oversight_info_struct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="has_dmc" type="{}yes_no_enum" minOccurs="0"/>
 *         &lt;element name="is_fda_regulated_drug" type="{}yes_no_enum" minOccurs="0"/>
 *         &lt;element name="is_fda_regulated_device" type="{}yes_no_enum" minOccurs="0"/>
 *         &lt;element name="is_unapproved_device" type="{}yes_no_enum" minOccurs="0"/>
 *         &lt;element name="is_ppsd" type="{}yes_no_enum" minOccurs="0"/>
 *         &lt;element name="is_us_export" type="{}yes_no_enum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oversight_info_struct", propOrder = {
    "hasDmc",
    "isFdaRegulatedDrug",
    "isFdaRegulatedDevice",
    "isUnapprovedDevice",
    "isPpsd",
    "isUsExport"
})
public class OversightInfoStruct
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "has_dmc")
    @XmlSchemaType(name = "string")
    protected YesNoEnum hasDmc;
    @XmlElement(name = "is_fda_regulated_drug")
    @XmlSchemaType(name = "string")
    protected YesNoEnum isFdaRegulatedDrug;
    @XmlElement(name = "is_fda_regulated_device")
    @XmlSchemaType(name = "string")
    protected YesNoEnum isFdaRegulatedDevice;
    @XmlElement(name = "is_unapproved_device")
    @XmlSchemaType(name = "string")
    protected YesNoEnum isUnapprovedDevice;
    @XmlElement(name = "is_ppsd")
    @XmlSchemaType(name = "string")
    protected YesNoEnum isPpsd;
    @XmlElement(name = "is_us_export")
    @XmlSchemaType(name = "string")
    protected YesNoEnum isUsExport;

    /**
     * Gets the value of the hasDmc property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoEnum }
     *     
     */
    public YesNoEnum getHasDmc() {
        return hasDmc;
    }

    /**
     * Sets the value of the hasDmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoEnum }
     *     
     */
    public void setHasDmc(YesNoEnum value) {
        this.hasDmc = value;
    }

    /**
     * Gets the value of the isFdaRegulatedDrug property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoEnum }
     *     
     */
    public YesNoEnum getIsFdaRegulatedDrug() {
        return isFdaRegulatedDrug;
    }

    /**
     * Sets the value of the isFdaRegulatedDrug property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoEnum }
     *     
     */
    public void setIsFdaRegulatedDrug(YesNoEnum value) {
        this.isFdaRegulatedDrug = value;
    }

    /**
     * Gets the value of the isFdaRegulatedDevice property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoEnum }
     *     
     */
    public YesNoEnum getIsFdaRegulatedDevice() {
        return isFdaRegulatedDevice;
    }

    /**
     * Sets the value of the isFdaRegulatedDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoEnum }
     *     
     */
    public void setIsFdaRegulatedDevice(YesNoEnum value) {
        this.isFdaRegulatedDevice = value;
    }

    /**
     * Gets the value of the isUnapprovedDevice property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoEnum }
     *     
     */
    public YesNoEnum getIsUnapprovedDevice() {
        return isUnapprovedDevice;
    }

    /**
     * Sets the value of the isUnapprovedDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoEnum }
     *     
     */
    public void setIsUnapprovedDevice(YesNoEnum value) {
        this.isUnapprovedDevice = value;
    }

    /**
     * Gets the value of the isPpsd property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoEnum }
     *     
     */
    public YesNoEnum getIsPpsd() {
        return isPpsd;
    }

    /**
     * Sets the value of the isPpsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoEnum }
     *     
     */
    public void setIsPpsd(YesNoEnum value) {
        this.isPpsd = value;
    }

    /**
     * Gets the value of the isUsExport property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoEnum }
     *     
     */
    public YesNoEnum getIsUsExport() {
        return isUsExport;
    }

    /**
     * Sets the value of the isUsExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoEnum }
     *     
     */
    public void setIsUsExport(YesNoEnum value) {
        this.isUsExport = value;
    }

}
