//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 12:59:43 PM CDT 
//


package edu.utdallas.hltri.data.clinical_trials.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for study_type_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="study_type_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Expanded Access"/>
 *     &lt;enumeration value="Interventional"/>
 *     &lt;enumeration value="N/A"/>
 *     &lt;enumeration value="Observational"/>
 *     &lt;enumeration value="Observational [Patient Registry]"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "study_type_enum")
@XmlEnum
public enum StudyTypeEnum {

    @XmlEnumValue("Expanded Access")
    EXPANDED_ACCESS("Expanded Access"),
    @XmlEnumValue("Interventional")
    INTERVENTIONAL("Interventional"),
    @XmlEnumValue("N/A")
    N_A("N/A"),
    @XmlEnumValue("Observational")
    OBSERVATIONAL("Observational"),
    @XmlEnumValue("Observational [Patient Registry]")
    OBSERVATIONAL_PATIENT_REGISTRY("Observational [Patient Registry]");
    private final String value;

    StudyTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StudyTypeEnum fromValue(String v) {
        for (StudyTypeEnum c: StudyTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
