//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Journal"/&gt;
 *         &lt;element ref="{}ArticleTitle"/&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{}Pagination"/&gt;
 *             &lt;element ref="{}ELocationID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element ref="{}ELocationID" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}Abstract" minOccurs="0"/&gt;
 *         &lt;element ref="{}AuthorList" minOccurs="0"/&gt;
 *         &lt;element ref="{}Language" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}DataBankList" minOccurs="0"/&gt;
 *         &lt;element ref="{}GrantList" minOccurs="0"/&gt;
 *         &lt;element ref="{}PublicationTypeList"/&gt;
 *         &lt;element ref="{}VernacularTitle" minOccurs="0"/&gt;
 *         &lt;element ref="{}ArticleDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="PubModel" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Print"/&gt;
 *             &lt;enumeration value="Print-Electronic"/&gt;
 *             &lt;enumeration value="Electronic"/&gt;
 *             &lt;enumeration value="Electronic-Print"/&gt;
 *             &lt;enumeration value="Electronic-eCollection"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journal",
    "articleTitle",
    "pagination",
    "eLocationIDs",
    "_abstract",
    "authorList",
    "languages",
    "dataBankList",
    "grantList",
    "publicationTypes",
    "vernacularTitle",
    "articleDates"
})
@XmlRootElement(name = "Article")
public class Article implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Journal", required = true)
    protected Journal journal;
    @XmlElement(name = "ArticleTitle", required = true)
    protected ArticleTitle articleTitle;
    @XmlElement(name = "Pagination")
    protected Pagination pagination;
    @XmlElement(name = "ELocationID")
    protected List<ELocationID> eLocationIDs;
    @XmlElement(name = "Abstract")
    protected Abstract _abstract;
    @XmlElement(name = "AuthorList")
    protected AuthorList authorList;
    @XmlElement(name = "Language", required = true)
    protected List<String> languages;
    @XmlElement(name = "DataBankList")
    protected DataBankList dataBankList;
    @XmlElement(name = "GrantList")
    protected GrantList grantList;
    @XmlElement(name = "PublicationTypeList", required = true)
    protected PublicationTypes publicationTypes;
    @XmlElement(name = "VernacularTitle")
    protected VernacularTitle vernacularTitle;
    @XmlElement(name = "ArticleDate")
    protected List<ArticleDate> articleDates;
    @XmlAttribute(name = "PubModel", required = true)
    protected String pubModel;

    /**
     * Gets the value of the journal property.
     * 
     * @return
     *     possible object is
     *     {@link Journal }
     *     
     */
    public Journal getJournal() {
        return journal;
    }

    /**
     * Sets the value of the journal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Journal }
     *     
     */
    public void setJournal(Journal value) {
        this.journal = value;
    }

    /**
     * Gets the value of the articleTitle property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleTitle }
     *     
     */
    public ArticleTitle getArticleTitle() {
        return articleTitle;
    }

    /**
     * Sets the value of the articleTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleTitle }
     *     
     */
    public void setArticleTitle(ArticleTitle value) {
        this.articleTitle = value;
    }

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link Pagination }
     *     
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagination }
     *     
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the eLocationIDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eLocationIDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getELocationIDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ELocationID }
     * 
     * 
     */
    public List<ELocationID> getELocationIDs() {
        if (eLocationIDs == null) {
            eLocationIDs = new ArrayList<ELocationID>();
        }
        return this.eLocationIDs;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Abstract }
     *     
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abstract }
     *     
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the authorList property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorList }
     *     
     */
    public AuthorList getAuthorList() {
        return authorList;
    }

    /**
     * Sets the value of the authorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorList }
     *     
     */
    public void setAuthorList(AuthorList value) {
        this.authorList = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguages() {
        if (languages == null) {
            languages = new ArrayList<String>();
        }
        return this.languages;
    }

    /**
     * Gets the value of the dataBankList property.
     * 
     * @return
     *     possible object is
     *     {@link DataBankList }
     *     
     */
    public DataBankList getDataBankList() {
        return dataBankList;
    }

    /**
     * Sets the value of the dataBankList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataBankList }
     *     
     */
    public void setDataBankList(DataBankList value) {
        this.dataBankList = value;
    }

    /**
     * Gets the value of the grantList property.
     * 
     * @return
     *     possible object is
     *     {@link GrantList }
     *     
     */
    public GrantList getGrantList() {
        return grantList;
    }

    /**
     * Sets the value of the grantList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrantList }
     *     
     */
    public void setGrantList(GrantList value) {
        this.grantList = value;
    }

    /**
     * Gets the value of the publicationTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationTypes }
     *     
     */
    public PublicationTypes getPublicationTypes() {
        return publicationTypes;
    }

    /**
     * Sets the value of the publicationTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationTypes }
     *     
     */
    public void setPublicationTypes(PublicationTypes value) {
        this.publicationTypes = value;
    }

    /**
     * Gets the value of the vernacularTitle property.
     * 
     * @return
     *     possible object is
     *     {@link VernacularTitle }
     *     
     */
    public VernacularTitle getVernacularTitle() {
        return vernacularTitle;
    }

    /**
     * Sets the value of the vernacularTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VernacularTitle }
     *     
     */
    public void setVernacularTitle(VernacularTitle value) {
        this.vernacularTitle = value;
    }

    /**
     * Gets the value of the articleDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArticleDate }
     * 
     * 
     */
    public List<ArticleDate> getArticleDates() {
        if (articleDates == null) {
            articleDates = new ArrayList<ArticleDate>();
        }
        return this.articleDates;
    }

    /**
     * Gets the value of the pubModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubModel() {
        return pubModel;
    }

    /**
     * Sets the value of the pubModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubModel(String value) {
        this.pubModel = value;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Article that = ((Article) object);
        {
            Journal leftJournal;
            leftJournal = this.getJournal();
            Journal rightJournal;
            rightJournal = that.getJournal();
            if (this.journal!= null) {
                if (that.journal!= null) {
                    if (!leftJournal.equals(rightJournal)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.journal!= null) {
                    return false;
                }
            }
        }
        {
            ArticleTitle leftArticleTitle;
            leftArticleTitle = this.getArticleTitle();
            ArticleTitle rightArticleTitle;
            rightArticleTitle = that.getArticleTitle();
            if (this.articleTitle!= null) {
                if (that.articleTitle!= null) {
                    if (!leftArticleTitle.equals(rightArticleTitle)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.articleTitle!= null) {
                    return false;
                }
            }
        }
        {
            Pagination leftPagination;
            leftPagination = this.getPagination();
            Pagination rightPagination;
            rightPagination = that.getPagination();
            if (this.pagination!= null) {
                if (that.pagination!= null) {
                    if (!leftPagination.equals(rightPagination)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.pagination!= null) {
                    return false;
                }
            }
        }
        {
            List<ELocationID> leftELocationIDs;
            leftELocationIDs = (((this.eLocationIDs!= null)&&(!this.eLocationIDs.isEmpty()))?this.getELocationIDs():null);
            List<ELocationID> rightELocationIDs;
            rightELocationIDs = (((that.eLocationIDs!= null)&&(!that.eLocationIDs.isEmpty()))?that.getELocationIDs():null);
            if ((this.eLocationIDs!= null)&&(!this.eLocationIDs.isEmpty())) {
                if ((that.eLocationIDs!= null)&&(!that.eLocationIDs.isEmpty())) {
                    if (!leftELocationIDs.equals(rightELocationIDs)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.eLocationIDs!= null)&&(!that.eLocationIDs.isEmpty())) {
                    return false;
                }
            }
        }
        {
            Abstract leftAbstract;
            leftAbstract = this.getAbstract();
            Abstract rightAbstract;
            rightAbstract = that.getAbstract();
            if (this._abstract!= null) {
                if (that._abstract!= null) {
                    if (!leftAbstract.equals(rightAbstract)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that._abstract!= null) {
                    return false;
                }
            }
        }
        {
            AuthorList leftAuthorList;
            leftAuthorList = this.getAuthorList();
            AuthorList rightAuthorList;
            rightAuthorList = that.getAuthorList();
            if (this.authorList!= null) {
                if (that.authorList!= null) {
                    if (!leftAuthorList.equals(rightAuthorList)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.authorList!= null) {
                    return false;
                }
            }
        }
        {
            List<String> leftLanguages;
            leftLanguages = (((this.languages!= null)&&(!this.languages.isEmpty()))?this.getLanguages():null);
            List<String> rightLanguages;
            rightLanguages = (((that.languages!= null)&&(!that.languages.isEmpty()))?that.getLanguages():null);
            if ((this.languages!= null)&&(!this.languages.isEmpty())) {
                if ((that.languages!= null)&&(!that.languages.isEmpty())) {
                    if (!leftLanguages.equals(rightLanguages)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.languages!= null)&&(!that.languages.isEmpty())) {
                    return false;
                }
            }
        }
        {
            DataBankList leftDataBankList;
            leftDataBankList = this.getDataBankList();
            DataBankList rightDataBankList;
            rightDataBankList = that.getDataBankList();
            if (this.dataBankList!= null) {
                if (that.dataBankList!= null) {
                    if (!leftDataBankList.equals(rightDataBankList)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.dataBankList!= null) {
                    return false;
                }
            }
        }
        {
            GrantList leftGrantList;
            leftGrantList = this.getGrantList();
            GrantList rightGrantList;
            rightGrantList = that.getGrantList();
            if (this.grantList!= null) {
                if (that.grantList!= null) {
                    if (!leftGrantList.equals(rightGrantList)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.grantList!= null) {
                    return false;
                }
            }
        }
        {
            PublicationTypes leftPublicationTypes;
            leftPublicationTypes = this.getPublicationTypes();
            PublicationTypes rightPublicationTypes;
            rightPublicationTypes = that.getPublicationTypes();
            if (this.publicationTypes != null) {
                if (that.publicationTypes != null) {
                    if (!leftPublicationTypes.equals(rightPublicationTypes)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.publicationTypes != null) {
                    return false;
                }
            }
        }
        {
            VernacularTitle leftVernacularTitle;
            leftVernacularTitle = this.getVernacularTitle();
            VernacularTitle rightVernacularTitle;
            rightVernacularTitle = that.getVernacularTitle();
            if (this.vernacularTitle!= null) {
                if (that.vernacularTitle!= null) {
                    if (!leftVernacularTitle.equals(rightVernacularTitle)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.vernacularTitle!= null) {
                    return false;
                }
            }
        }
        {
            List<ArticleDate> leftArticleDates;
            leftArticleDates = (((this.articleDates!= null)&&(!this.articleDates.isEmpty()))?this.getArticleDates():null);
            List<ArticleDate> rightArticleDates;
            rightArticleDates = (((that.articleDates!= null)&&(!that.articleDates.isEmpty()))?that.getArticleDates():null);
            if ((this.articleDates!= null)&&(!this.articleDates.isEmpty())) {
                if ((that.articleDates!= null)&&(!that.articleDates.isEmpty())) {
                    if (!leftArticleDates.equals(rightArticleDates)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.articleDates!= null)&&(!that.articleDates.isEmpty())) {
                    return false;
                }
            }
        }
        {
            String leftPubModel;
            leftPubModel = this.getPubModel();
            String rightPubModel;
            rightPubModel = that.getPubModel();
            if (this.pubModel!= null) {
                if (that.pubModel!= null) {
                    if (!leftPubModel.equals(rightPubModel)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.pubModel!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            Journal theJournal;
            theJournal = this.getJournal();
            if (this.journal!= null) {
                currentHashCode += theJournal.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ArticleTitle theArticleTitle;
            theArticleTitle = this.getArticleTitle();
            if (this.articleTitle!= null) {
                currentHashCode += theArticleTitle.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            Pagination thePagination;
            thePagination = this.getPagination();
            if (this.pagination!= null) {
                currentHashCode += thePagination.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<ELocationID> theELocationIDs;
            theELocationIDs = (((this.eLocationIDs!= null)&&(!this.eLocationIDs.isEmpty()))?this.getELocationIDs():null);
            if ((this.eLocationIDs!= null)&&(!this.eLocationIDs.isEmpty())) {
                currentHashCode += theELocationIDs.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            Abstract theAbstract;
            theAbstract = this.getAbstract();
            if (this._abstract!= null) {
                currentHashCode += theAbstract.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            AuthorList theAuthorList;
            theAuthorList = this.getAuthorList();
            if (this.authorList!= null) {
                currentHashCode += theAuthorList.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<String> theLanguages;
            theLanguages = (((this.languages!= null)&&(!this.languages.isEmpty()))?this.getLanguages():null);
            if ((this.languages!= null)&&(!this.languages.isEmpty())) {
                currentHashCode += theLanguages.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            DataBankList theDataBankList;
            theDataBankList = this.getDataBankList();
            if (this.dataBankList!= null) {
                currentHashCode += theDataBankList.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            GrantList theGrantList;
            theGrantList = this.getGrantList();
            if (this.grantList!= null) {
                currentHashCode += theGrantList.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            PublicationTypes thePublicationTypes;
            thePublicationTypes = this.getPublicationTypes();
            if (this.publicationTypes != null) {
                currentHashCode += thePublicationTypes.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            VernacularTitle theVernacularTitle;
            theVernacularTitle = this.getVernacularTitle();
            if (this.vernacularTitle!= null) {
                currentHashCode += theVernacularTitle.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<ArticleDate> theArticleDates;
            theArticleDates = (((this.articleDates!= null)&&(!this.articleDates.isEmpty()))?this.getArticleDates():null);
            if ((this.articleDates!= null)&&(!this.articleDates.isEmpty())) {
                currentHashCode += theArticleDates.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String thePubModel;
            thePubModel = this.getPubModel();
            if (this.pubModel!= null) {
                currentHashCode += thePubModel.hashCode();
            }
        }
        return currentHashCode;
    }

}
