//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PMID"/&gt;
 *         &lt;element ref="{}ArticleIdList"/&gt;
 *         &lt;element ref="{}Book"/&gt;
 *         &lt;element ref="{}LocationLabel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ArticleTitle" minOccurs="0"/&gt;
 *         &lt;element ref="{}VernacularTitle" minOccurs="0"/&gt;
 *         &lt;element ref="{}Pagination" minOccurs="0"/&gt;
 *         &lt;element ref="{}Language" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}AuthorList" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}InvestigatorList" minOccurs="0"/&gt;
 *         &lt;element ref="{}PublicationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Abstract" minOccurs="0"/&gt;
 *         &lt;element ref="{}Sections" minOccurs="0"/&gt;
 *         &lt;element ref="{}KeywordList" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ContributionDate" minOccurs="0"/&gt;
 *         &lt;element ref="{}DateRevised" minOccurs="0"/&gt;
 *         &lt;element ref="{}CitationString" minOccurs="0"/&gt;
 *         &lt;element ref="{}GrantList" minOccurs="0"/&gt;
 *         &lt;element ref="{}ItemList" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pmid",
    "articleIdList",
    "book",
    "locationLabels",
    "articleTitle",
    "vernacularTitle",
    "pagination",
    "languages",
    "authorLists",
    "investigatorList",
    "publicationTypes",
    "_abstract",
    "sections",
    "keywordLists",
    "contributionDate",
    "dateRevised",
    "citationString",
    "grantList",
    "itemLists"
})
@XmlRootElement(name = "BookDocument")
public class BookDocument implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "PMID", required = true)
    protected PMID pmid;
    @XmlElement(name = "ArticleIdList", required = true)
    protected ArticleIdList articleIdList;
    @XmlElement(name = "Book", required = true)
    protected Book book;
    @XmlElement(name = "LocationLabel")
    protected List<LocationLabel> locationLabels;
    @XmlElement(name = "ArticleTitle")
    protected ArticleTitle articleTitle;
    @XmlElement(name = "VernacularTitle")
    protected VernacularTitle vernacularTitle;
    @XmlElement(name = "Pagination")
    protected Pagination pagination;
    @XmlElement(name = "Language")
    protected List<String> languages;
    @XmlElement(name = "AuthorList")
    protected List<AuthorList> authorLists;
    @XmlElement(name = "InvestigatorList")
    protected InvestigatorList investigatorList;
    @XmlElement(name = "PublicationType")
    protected List<PublicationType> publicationTypes;
    @XmlElement(name = "Abstract")
    protected Abstract _abstract;
    @XmlElement(name = "Sections")
    protected Sections sections;
    @XmlElement(name = "KeywordList")
    protected List<KeywordList> keywordLists;
    @XmlElement(name = "ContributionDate")
    protected ContributionDate contributionDate;
    @XmlElement(name = "DateRevised")
    protected DateRevised dateRevised;
    @XmlElement(name = "CitationString")
    protected CitationString citationString;
    @XmlElement(name = "GrantList")
    protected GrantList grantList;
    @XmlElement(name = "ItemList")
    protected List<ItemList> itemLists;

    /**
     * Gets the value of the pmid property.
     * 
     * @return
     *     possible object is
     *     {@link PMID }
     *     
     */
    public PMID getPMID() {
        return pmid;
    }

    /**
     * Sets the value of the pmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PMID }
     *     
     */
    public void setPMID(PMID value) {
        this.pmid = value;
    }

    /**
     * Gets the value of the articleIdList property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleIdList }
     *     
     */
    public ArticleIdList getArticleIdList() {
        return articleIdList;
    }

    /**
     * Sets the value of the articleIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleIdList }
     *     
     */
    public void setArticleIdList(ArticleIdList value) {
        this.articleIdList = value;
    }

    /**
     * Gets the value of the book property.
     * 
     * @return
     *     possible object is
     *     {@link Book }
     *     
     */
    public Book getBook() {
        return book;
    }

    /**
     * Sets the value of the book property.
     * 
     * @param value
     *     allowed object is
     *     {@link Book }
     *     
     */
    public void setBook(Book value) {
        this.book = value;
    }

    /**
     * Gets the value of the locationLabels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locationLabels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationLabels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationLabel }
     * 
     * 
     */
    public List<LocationLabel> getLocationLabels() {
        if (locationLabels == null) {
            locationLabels = new ArrayList<LocationLabel>();
        }
        return this.locationLabels;
    }

    /**
     * Gets the value of the articleTitle property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleTitle }
     *     
     */
    public ArticleTitle getArticleTitle() {
        return articleTitle;
    }

    /**
     * Sets the value of the articleTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleTitle }
     *     
     */
    public void setArticleTitle(ArticleTitle value) {
        this.articleTitle = value;
    }

    /**
     * Gets the value of the vernacularTitle property.
     * 
     * @return
     *     possible object is
     *     {@link VernacularTitle }
     *     
     */
    public VernacularTitle getVernacularTitle() {
        return vernacularTitle;
    }

    /**
     * Sets the value of the vernacularTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VernacularTitle }
     *     
     */
    public void setVernacularTitle(VernacularTitle value) {
        this.vernacularTitle = value;
    }

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link Pagination }
     *     
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagination }
     *     
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguages() {
        if (languages == null) {
            languages = new ArrayList<String>();
        }
        return this.languages;
    }

    /**
     * Gets the value of the authorLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorList }
     * 
     * 
     */
    public List<AuthorList> getAuthorLists() {
        if (authorLists == null) {
            authorLists = new ArrayList<AuthorList>();
        }
        return this.authorLists;
    }

    /**
     * Gets the value of the investigatorList property.
     * 
     * @return
     *     possible object is
     *     {@link InvestigatorList }
     *     
     */
    public InvestigatorList getInvestigatorList() {
        return investigatorList;
    }

    /**
     * Sets the value of the investigatorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestigatorList }
     *     
     */
    public void setInvestigatorList(InvestigatorList value) {
        this.investigatorList = value;
    }

    /**
     * Gets the value of the publicationTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publicationTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublicationTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicationType }
     * 
     * 
     */
    public List<PublicationType> getPublicationTypes() {
        if (publicationTypes == null) {
            publicationTypes = new ArrayList<PublicationType>();
        }
        return this.publicationTypes;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Abstract }
     *     
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abstract }
     *     
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the sections property.
     * 
     * @return
     *     possible object is
     *     {@link Sections }
     *     
     */
    public Sections getSections() {
        return sections;
    }

    /**
     * Sets the value of the sections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sections }
     *     
     */
    public void setSections(Sections value) {
        this.sections = value;
    }

    /**
     * Gets the value of the keywordLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywordLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywordLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeywordList }
     * 
     * 
     */
    public List<KeywordList> getKeywordLists() {
        if (keywordLists == null) {
            keywordLists = new ArrayList<KeywordList>();
        }
        return this.keywordLists;
    }

    /**
     * Gets the value of the contributionDate property.
     * 
     * @return
     *     possible object is
     *     {@link ContributionDate }
     *     
     */
    public ContributionDate getContributionDate() {
        return contributionDate;
    }

    /**
     * Sets the value of the contributionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContributionDate }
     *     
     */
    public void setContributionDate(ContributionDate value) {
        this.contributionDate = value;
    }

    /**
     * Gets the value of the dateRevised property.
     * 
     * @return
     *     possible object is
     *     {@link DateRevised }
     *     
     */
    public DateRevised getDateRevised() {
        return dateRevised;
    }

    /**
     * Sets the value of the dateRevised property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRevised }
     *     
     */
    public void setDateRevised(DateRevised value) {
        this.dateRevised = value;
    }

    /**
     * Gets the value of the citationString property.
     * 
     * @return
     *     possible object is
     *     {@link CitationString }
     *     
     */
    public CitationString getCitationString() {
        return citationString;
    }

    /**
     * Sets the value of the citationString property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationString }
     *     
     */
    public void setCitationString(CitationString value) {
        this.citationString = value;
    }

    /**
     * Gets the value of the grantList property.
     * 
     * @return
     *     possible object is
     *     {@link GrantList }
     *     
     */
    public GrantList getGrantList() {
        return grantList;
    }

    /**
     * Sets the value of the grantList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrantList }
     *     
     */
    public void setGrantList(GrantList value) {
        this.grantList = value;
    }

    /**
     * Gets the value of the itemLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemList }
     * 
     * 
     */
    public List<ItemList> getItemLists() {
        if (itemLists == null) {
            itemLists = new ArrayList<ItemList>();
        }
        return this.itemLists;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final BookDocument that = ((BookDocument) object);
        {
            PMID leftPMID;
            leftPMID = this.getPMID();
            PMID rightPMID;
            rightPMID = that.getPMID();
            if (this.pmid!= null) {
                if (that.pmid!= null) {
                    if (!leftPMID.equals(rightPMID)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.pmid!= null) {
                    return false;
                }
            }
        }
        {
            ArticleIdList leftArticleIdList;
            leftArticleIdList = this.getArticleIdList();
            ArticleIdList rightArticleIdList;
            rightArticleIdList = that.getArticleIdList();
            if (this.articleIdList!= null) {
                if (that.articleIdList!= null) {
                    if (!leftArticleIdList.equals(rightArticleIdList)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.articleIdList!= null) {
                    return false;
                }
            }
        }
        {
            Book leftBook;
            leftBook = this.getBook();
            Book rightBook;
            rightBook = that.getBook();
            if (this.book!= null) {
                if (that.book!= null) {
                    if (!leftBook.equals(rightBook)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.book!= null) {
                    return false;
                }
            }
        }
        {
            List<LocationLabel> leftLocationLabels;
            leftLocationLabels = (((this.locationLabels!= null)&&(!this.locationLabels.isEmpty()))?this.getLocationLabels():null);
            List<LocationLabel> rightLocationLabels;
            rightLocationLabels = (((that.locationLabels!= null)&&(!that.locationLabels.isEmpty()))?that.getLocationLabels():null);
            if ((this.locationLabels!= null)&&(!this.locationLabels.isEmpty())) {
                if ((that.locationLabels!= null)&&(!that.locationLabels.isEmpty())) {
                    if (!leftLocationLabels.equals(rightLocationLabels)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.locationLabels!= null)&&(!that.locationLabels.isEmpty())) {
                    return false;
                }
            }
        }
        {
            ArticleTitle leftArticleTitle;
            leftArticleTitle = this.getArticleTitle();
            ArticleTitle rightArticleTitle;
            rightArticleTitle = that.getArticleTitle();
            if (this.articleTitle!= null) {
                if (that.articleTitle!= null) {
                    if (!leftArticleTitle.equals(rightArticleTitle)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.articleTitle!= null) {
                    return false;
                }
            }
        }
        {
            VernacularTitle leftVernacularTitle;
            leftVernacularTitle = this.getVernacularTitle();
            VernacularTitle rightVernacularTitle;
            rightVernacularTitle = that.getVernacularTitle();
            if (this.vernacularTitle!= null) {
                if (that.vernacularTitle!= null) {
                    if (!leftVernacularTitle.equals(rightVernacularTitle)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.vernacularTitle!= null) {
                    return false;
                }
            }
        }
        {
            Pagination leftPagination;
            leftPagination = this.getPagination();
            Pagination rightPagination;
            rightPagination = that.getPagination();
            if (this.pagination!= null) {
                if (that.pagination!= null) {
                    if (!leftPagination.equals(rightPagination)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.pagination!= null) {
                    return false;
                }
            }
        }
        {
            List<String> leftLanguages;
            leftLanguages = (((this.languages!= null)&&(!this.languages.isEmpty()))?this.getLanguages():null);
            List<String> rightLanguages;
            rightLanguages = (((that.languages!= null)&&(!that.languages.isEmpty()))?that.getLanguages():null);
            if ((this.languages!= null)&&(!this.languages.isEmpty())) {
                if ((that.languages!= null)&&(!that.languages.isEmpty())) {
                    if (!leftLanguages.equals(rightLanguages)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.languages!= null)&&(!that.languages.isEmpty())) {
                    return false;
                }
            }
        }
        {
            List<AuthorList> leftAuthorLists;
            leftAuthorLists = (((this.authorLists!= null)&&(!this.authorLists.isEmpty()))?this.getAuthorLists():null);
            List<AuthorList> rightAuthorLists;
            rightAuthorLists = (((that.authorLists!= null)&&(!that.authorLists.isEmpty()))?that.getAuthorLists():null);
            if ((this.authorLists!= null)&&(!this.authorLists.isEmpty())) {
                if ((that.authorLists!= null)&&(!that.authorLists.isEmpty())) {
                    if (!leftAuthorLists.equals(rightAuthorLists)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.authorLists!= null)&&(!that.authorLists.isEmpty())) {
                    return false;
                }
            }
        }
        {
            InvestigatorList leftInvestigatorList;
            leftInvestigatorList = this.getInvestigatorList();
            InvestigatorList rightInvestigatorList;
            rightInvestigatorList = that.getInvestigatorList();
            if (this.investigatorList!= null) {
                if (that.investigatorList!= null) {
                    if (!leftInvestigatorList.equals(rightInvestigatorList)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.investigatorList!= null) {
                    return false;
                }
            }
        }
        {
            List<PublicationType> leftPublicationTypes;
            leftPublicationTypes = (((this.publicationTypes!= null)&&(!this.publicationTypes.isEmpty()))?this.getPublicationTypes():null);
            List<PublicationType> rightPublicationTypes;
            rightPublicationTypes = (((that.publicationTypes!= null)&&(!that.publicationTypes.isEmpty()))?that.getPublicationTypes():null);
            if ((this.publicationTypes!= null)&&(!this.publicationTypes.isEmpty())) {
                if ((that.publicationTypes!= null)&&(!that.publicationTypes.isEmpty())) {
                    if (!leftPublicationTypes.equals(rightPublicationTypes)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.publicationTypes!= null)&&(!that.publicationTypes.isEmpty())) {
                    return false;
                }
            }
        }
        {
            Abstract leftAbstract;
            leftAbstract = this.getAbstract();
            Abstract rightAbstract;
            rightAbstract = that.getAbstract();
            if (this._abstract!= null) {
                if (that._abstract!= null) {
                    if (!leftAbstract.equals(rightAbstract)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that._abstract!= null) {
                    return false;
                }
            }
        }
        {
            Sections leftSections;
            leftSections = this.getSections();
            Sections rightSections;
            rightSections = that.getSections();
            if (this.sections!= null) {
                if (that.sections!= null) {
                    if (!leftSections.equals(rightSections)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.sections!= null) {
                    return false;
                }
            }
        }
        {
            List<KeywordList> leftKeywordLists;
            leftKeywordLists = (((this.keywordLists!= null)&&(!this.keywordLists.isEmpty()))?this.getKeywordLists():null);
            List<KeywordList> rightKeywordLists;
            rightKeywordLists = (((that.keywordLists!= null)&&(!that.keywordLists.isEmpty()))?that.getKeywordLists():null);
            if ((this.keywordLists!= null)&&(!this.keywordLists.isEmpty())) {
                if ((that.keywordLists!= null)&&(!that.keywordLists.isEmpty())) {
                    if (!leftKeywordLists.equals(rightKeywordLists)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.keywordLists!= null)&&(!that.keywordLists.isEmpty())) {
                    return false;
                }
            }
        }
        {
            ContributionDate leftContributionDate;
            leftContributionDate = this.getContributionDate();
            ContributionDate rightContributionDate;
            rightContributionDate = that.getContributionDate();
            if (this.contributionDate!= null) {
                if (that.contributionDate!= null) {
                    if (!leftContributionDate.equals(rightContributionDate)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.contributionDate!= null) {
                    return false;
                }
            }
        }
        {
            DateRevised leftDateRevised;
            leftDateRevised = this.getDateRevised();
            DateRevised rightDateRevised;
            rightDateRevised = that.getDateRevised();
            if (this.dateRevised!= null) {
                if (that.dateRevised!= null) {
                    if (!leftDateRevised.equals(rightDateRevised)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.dateRevised!= null) {
                    return false;
                }
            }
        }
        {
            CitationString leftCitationString;
            leftCitationString = this.getCitationString();
            CitationString rightCitationString;
            rightCitationString = that.getCitationString();
            if (this.citationString!= null) {
                if (that.citationString!= null) {
                    if (!leftCitationString.equals(rightCitationString)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.citationString!= null) {
                    return false;
                }
            }
        }
        {
            GrantList leftGrantList;
            leftGrantList = this.getGrantList();
            GrantList rightGrantList;
            rightGrantList = that.getGrantList();
            if (this.grantList!= null) {
                if (that.grantList!= null) {
                    if (!leftGrantList.equals(rightGrantList)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.grantList!= null) {
                    return false;
                }
            }
        }
        {
            List<ItemList> leftItemLists;
            leftItemLists = (((this.itemLists!= null)&&(!this.itemLists.isEmpty()))?this.getItemLists():null);
            List<ItemList> rightItemLists;
            rightItemLists = (((that.itemLists!= null)&&(!that.itemLists.isEmpty()))?that.getItemLists():null);
            if ((this.itemLists!= null)&&(!this.itemLists.isEmpty())) {
                if ((that.itemLists!= null)&&(!that.itemLists.isEmpty())) {
                    if (!leftItemLists.equals(rightItemLists)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.itemLists!= null)&&(!that.itemLists.isEmpty())) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            PMID thePMID;
            thePMID = this.getPMID();
            if (this.pmid!= null) {
                currentHashCode += thePMID.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ArticleIdList theArticleIdList;
            theArticleIdList = this.getArticleIdList();
            if (this.articleIdList!= null) {
                currentHashCode += theArticleIdList.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            Book theBook;
            theBook = this.getBook();
            if (this.book!= null) {
                currentHashCode += theBook.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<LocationLabel> theLocationLabels;
            theLocationLabels = (((this.locationLabels!= null)&&(!this.locationLabels.isEmpty()))?this.getLocationLabels():null);
            if ((this.locationLabels!= null)&&(!this.locationLabels.isEmpty())) {
                currentHashCode += theLocationLabels.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ArticleTitle theArticleTitle;
            theArticleTitle = this.getArticleTitle();
            if (this.articleTitle!= null) {
                currentHashCode += theArticleTitle.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            VernacularTitle theVernacularTitle;
            theVernacularTitle = this.getVernacularTitle();
            if (this.vernacularTitle!= null) {
                currentHashCode += theVernacularTitle.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            Pagination thePagination;
            thePagination = this.getPagination();
            if (this.pagination!= null) {
                currentHashCode += thePagination.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<String> theLanguages;
            theLanguages = (((this.languages!= null)&&(!this.languages.isEmpty()))?this.getLanguages():null);
            if ((this.languages!= null)&&(!this.languages.isEmpty())) {
                currentHashCode += theLanguages.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<AuthorList> theAuthorLists;
            theAuthorLists = (((this.authorLists!= null)&&(!this.authorLists.isEmpty()))?this.getAuthorLists():null);
            if ((this.authorLists!= null)&&(!this.authorLists.isEmpty())) {
                currentHashCode += theAuthorLists.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            InvestigatorList theInvestigatorList;
            theInvestigatorList = this.getInvestigatorList();
            if (this.investigatorList!= null) {
                currentHashCode += theInvestigatorList.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<PublicationType> thePublicationTypes;
            thePublicationTypes = (((this.publicationTypes!= null)&&(!this.publicationTypes.isEmpty()))?this.getPublicationTypes():null);
            if ((this.publicationTypes!= null)&&(!this.publicationTypes.isEmpty())) {
                currentHashCode += thePublicationTypes.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            Abstract theAbstract;
            theAbstract = this.getAbstract();
            if (this._abstract!= null) {
                currentHashCode += theAbstract.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            Sections theSections;
            theSections = this.getSections();
            if (this.sections!= null) {
                currentHashCode += theSections.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<KeywordList> theKeywordLists;
            theKeywordLists = (((this.keywordLists!= null)&&(!this.keywordLists.isEmpty()))?this.getKeywordLists():null);
            if ((this.keywordLists!= null)&&(!this.keywordLists.isEmpty())) {
                currentHashCode += theKeywordLists.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ContributionDate theContributionDate;
            theContributionDate = this.getContributionDate();
            if (this.contributionDate!= null) {
                currentHashCode += theContributionDate.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            DateRevised theDateRevised;
            theDateRevised = this.getDateRevised();
            if (this.dateRevised!= null) {
                currentHashCode += theDateRevised.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            CitationString theCitationString;
            theCitationString = this.getCitationString();
            if (this.citationString!= null) {
                currentHashCode += theCitationString.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            GrantList theGrantList;
            theGrantList = this.getGrantList();
            if (this.grantList!= null) {
                currentHashCode += theGrantList.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<ItemList> theItemLists;
            theItemLists = (((this.itemLists!= null)&&(!this.itemLists.isEmpty()))?this.getItemLists():null);
            if ((this.itemLists!= null)&&(!this.itemLists.isEmpty())) {
                currentHashCode += theItemLists.hashCode();
            }
        }
        return currentHashCode;
    }

}
