//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}CommentsCorrections" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commentsCorrections"
})
@XmlRootElement(name = "CommentsCorrectionsList")
public class CommentsCorrectionsList implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CommentsCorrections", required = true)
    protected List<CommentsCorrections> commentsCorrections;

    /**
     * Gets the value of the commentsCorrections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commentsCorrections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommentsCorrections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentsCorrections }
     * 
     * 
     */
    public List<CommentsCorrections> getCommentsCorrections() {
        if (commentsCorrections == null) {
            commentsCorrections = new ArrayList<CommentsCorrections>();
        }
        return this.commentsCorrections;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CommentsCorrectionsList that = ((CommentsCorrectionsList) object);
        {
            List<CommentsCorrections> leftCommentsCorrections;
            leftCommentsCorrections = (((this.commentsCorrections!= null)&&(!this.commentsCorrections.isEmpty()))?this.getCommentsCorrections():null);
            List<CommentsCorrections> rightCommentsCorrections;
            rightCommentsCorrections = (((that.commentsCorrections!= null)&&(!that.commentsCorrections.isEmpty()))?that.getCommentsCorrections():null);
            if ((this.commentsCorrections!= null)&&(!this.commentsCorrections.isEmpty())) {
                if ((that.commentsCorrections!= null)&&(!that.commentsCorrections.isEmpty())) {
                    if (!leftCommentsCorrections.equals(rightCommentsCorrections)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.commentsCorrections!= null)&&(!that.commentsCorrections.isEmpty())) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            List<CommentsCorrections> theCommentsCorrections;
            theCommentsCorrections = (((this.commentsCorrections!= null)&&(!this.commentsCorrections.isEmpty()))?this.getCommentsCorrections():null);
            if ((this.commentsCorrections!= null)&&(!this.commentsCorrections.isEmpty())) {
                currentHashCode += theCommentsCorrections.hashCode();
            }
        }
        return currentHashCode;
    }

}
