//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}GeneSymbol" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geneSymbols"
})
@XmlRootElement(name = "GeneSymbolList")
public class GeneSymbolList implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "GeneSymbol", required = true)
    protected List<String> geneSymbols;

    /**
     * Gets the value of the geneSymbols property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geneSymbols property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneSymbols().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGeneSymbols() {
        if (geneSymbols == null) {
            geneSymbols = new ArrayList<String>();
        }
        return this.geneSymbols;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final GeneSymbolList that = ((GeneSymbolList) object);
        {
            List<String> leftGeneSymbols;
            leftGeneSymbols = (((this.geneSymbols!= null)&&(!this.geneSymbols.isEmpty()))?this.getGeneSymbols():null);
            List<String> rightGeneSymbols;
            rightGeneSymbols = (((that.geneSymbols!= null)&&(!that.geneSymbols.isEmpty()))?that.getGeneSymbols():null);
            if ((this.geneSymbols!= null)&&(!this.geneSymbols.isEmpty())) {
                if ((that.geneSymbols!= null)&&(!that.geneSymbols.isEmpty())) {
                    if (!leftGeneSymbols.equals(rightGeneSymbols)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.geneSymbols!= null)&&(!that.geneSymbols.isEmpty())) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            List<String> theGeneSymbols;
            theGeneSymbols = (((this.geneSymbols!= null)&&(!this.geneSymbols.isEmpty()))?this.getGeneSymbols():null);
            if ((this.geneSymbols!= null)&&(!this.geneSymbols.isEmpty())) {
                currentHashCode += theGeneSymbols.hashCode();
            }
        }
        return currentHashCode;
    }

}
