//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Grant" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CompleteYN" default="Y"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Y"/&gt;
 *             &lt;enumeration value="N"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "grants"
})
@XmlRootElement(name = "GrantList")
public class GrantList implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Grant", required = true)
    protected List<Grant> grants;
    @XmlAttribute(name = "CompleteYN")
    protected String completeYN;

    /**
     * Gets the value of the grants property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grants property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrants().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Grant }
     * 
     * 
     */
    public List<Grant> getGrants() {
        if (grants == null) {
            grants = new ArrayList<Grant>();
        }
        return this.grants;
    }

    /**
     * Gets the value of the completeYN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompleteYN() {
        if (completeYN == null) {
            return "Y";
        } else {
            return completeYN;
        }
    }

    /**
     * Sets the value of the completeYN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompleteYN(String value) {
        this.completeYN = value;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final GrantList that = ((GrantList) object);
        {
            List<Grant> leftGrants;
            leftGrants = (((this.grants!= null)&&(!this.grants.isEmpty()))?this.getGrants():null);
            List<Grant> rightGrants;
            rightGrants = (((that.grants!= null)&&(!that.grants.isEmpty()))?that.getGrants():null);
            if ((this.grants!= null)&&(!this.grants.isEmpty())) {
                if ((that.grants!= null)&&(!that.grants.isEmpty())) {
                    if (!leftGrants.equals(rightGrants)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.grants!= null)&&(!that.grants.isEmpty())) {
                    return false;
                }
            }
        }
        {
            String leftCompleteYN;
            leftCompleteYN = this.getCompleteYN();
            String rightCompleteYN;
            rightCompleteYN = that.getCompleteYN();
            if (this.completeYN!= null) {
                if (that.completeYN!= null) {
                    if (!leftCompleteYN.equals(rightCompleteYN)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.completeYN!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            List<Grant> theGrants;
            theGrants = (((this.grants!= null)&&(!this.grants.isEmpty()))?this.getGrants():null);
            if ((this.grants!= null)&&(!this.grants.isEmpty())) {
                currentHashCode += theGrants.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theCompleteYN;
            theCompleteYN = this.getCompleteYN();
            if (this.completeYN!= null) {
                currentHashCode += theCompleteYN.hashCode();
            }
        }
        return currentHashCode;
    }

}
