//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PubMedPubDate" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pubMedPubDates"
})
@XmlRootElement(name = "History")
public class History implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "PubMedPubDate", required = true)
    protected List<PubMedPubDate> pubMedPubDates;

    /**
     * Gets the value of the pubMedPubDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pubMedPubDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPubMedPubDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PubMedPubDate }
     * 
     * 
     */
    public List<PubMedPubDate> getPubMedPubDates() {
        if (pubMedPubDates == null) {
            pubMedPubDates = new ArrayList<PubMedPubDate>();
        }
        return this.pubMedPubDates;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final History that = ((History) object);
        {
            List<PubMedPubDate> leftPubMedPubDates;
            leftPubMedPubDates = (((this.pubMedPubDates!= null)&&(!this.pubMedPubDates.isEmpty()))?this.getPubMedPubDates():null);
            List<PubMedPubDate> rightPubMedPubDates;
            rightPubMedPubDates = (((that.pubMedPubDates!= null)&&(!that.pubMedPubDates.isEmpty()))?that.getPubMedPubDates():null);
            if ((this.pubMedPubDates!= null)&&(!this.pubMedPubDates.isEmpty())) {
                if ((that.pubMedPubDates!= null)&&(!that.pubMedPubDates.isEmpty())) {
                    if (!leftPubMedPubDates.equals(rightPubMedPubDates)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.pubMedPubDates!= null)&&(!that.pubMedPubDates.isEmpty())) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            List<PubMedPubDate> thePubMedPubDates;
            thePubMedPubDates = (((this.pubMedPubDates!= null)&&(!this.pubMedPubDates.isEmpty()))?this.getPubMedPubDates():null);
            if ((this.pubMedPubDates!= null)&&(!this.pubMedPubDates.isEmpty())) {
                currentHashCode += thePubMedPubDates.hashCode();
            }
        }
        return currentHashCode;
    }

}
