//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Volume" minOccurs="0"/&gt;
 *         &lt;element ref="{}Issue" minOccurs="0"/&gt;
 *         &lt;element ref="{}PubDate"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CitedMedium" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Internet"/&gt;
 *             &lt;enumeration value="Print"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "volume",
    "issue",
    "pubDate"
})
@XmlRootElement(name = "JournalIssue")
public class JournalIssue implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Volume")
    protected String volume;
    @XmlElement(name = "Issue")
    protected String issue;
    @XmlElement(name = "PubDate", required = true)
    protected PubDate pubDate;
    @XmlAttribute(name = "CitedMedium", required = true)
    protected String citedMedium;

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolume(String value) {
        this.volume = value;
    }

    /**
     * Gets the value of the issue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssue(String value) {
        this.issue = value;
    }

    /**
     * Gets the value of the pubDate property.
     * 
     * @return
     *     possible object is
     *     {@link PubDate }
     *     
     */
    public PubDate getPubDate() {
        return pubDate;
    }

    /**
     * Sets the value of the pubDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PubDate }
     *     
     */
    public void setPubDate(PubDate value) {
        this.pubDate = value;
    }

    /**
     * Gets the value of the citedMedium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitedMedium() {
        return citedMedium;
    }

    /**
     * Sets the value of the citedMedium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitedMedium(String value) {
        this.citedMedium = value;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final JournalIssue that = ((JournalIssue) object);
        {
            String leftVolume;
            leftVolume = this.getVolume();
            String rightVolume;
            rightVolume = that.getVolume();
            if (this.volume!= null) {
                if (that.volume!= null) {
                    if (!leftVolume.equals(rightVolume)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.volume!= null) {
                    return false;
                }
            }
        }
        {
            String leftIssue;
            leftIssue = this.getIssue();
            String rightIssue;
            rightIssue = that.getIssue();
            if (this.issue!= null) {
                if (that.issue!= null) {
                    if (!leftIssue.equals(rightIssue)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.issue!= null) {
                    return false;
                }
            }
        }
        {
            PubDate leftPubDate;
            leftPubDate = this.getPubDate();
            PubDate rightPubDate;
            rightPubDate = that.getPubDate();
            if (this.pubDate!= null) {
                if (that.pubDate!= null) {
                    if (!leftPubDate.equals(rightPubDate)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.pubDate!= null) {
                    return false;
                }
            }
        }
        {
            String leftCitedMedium;
            leftCitedMedium = this.getCitedMedium();
            String rightCitedMedium;
            rightCitedMedium = that.getCitedMedium();
            if (this.citedMedium!= null) {
                if (that.citedMedium!= null) {
                    if (!leftCitedMedium.equals(rightCitedMedium)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.citedMedium!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            String theVolume;
            theVolume = this.getVolume();
            if (this.volume!= null) {
                currentHashCode += theVolume.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theIssue;
            theIssue = this.getIssue();
            if (this.issue!= null) {
                currentHashCode += theIssue.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            PubDate thePubDate;
            thePubDate = this.getPubDate();
            if (this.pubDate!= null) {
                currentHashCode += thePubDate.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theCitedMedium;
            theCitedMedium = this.getCitedMedium();
            if (this.citedMedium!= null) {
                currentHashCode += theCitedMedium.hashCode();
            }
        }
        return currentHashCode;
    }

}
