//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Keyword" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Owner" default="NLM"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="NLM"/&gt;
 *             &lt;enumeration value="NLM-AUTO"/&gt;
 *             &lt;enumeration value="NASA"/&gt;
 *             &lt;enumeration value="PIP"/&gt;
 *             &lt;enumeration value="KIE"/&gt;
 *             &lt;enumeration value="NOTNLM"/&gt;
 *             &lt;enumeration value="HHS"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "keywords"
})
@XmlRootElement(name = "KeywordList")
public class KeywordList implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Keyword", required = true)
    protected List<Keyword> keywords;
    @XmlAttribute(name = "Owner")
    protected String owner;

    /**
     * Gets the value of the keywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Keyword }
     * 
     * 
     */
    public List<Keyword> getKeywords() {
        if (keywords == null) {
            keywords = new ArrayList<Keyword>();
        }
        return this.keywords;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        if (owner == null) {
            return "NLM";
        } else {
            return owner;
        }
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final KeywordList that = ((KeywordList) object);
        {
            List<Keyword> leftKeywords;
            leftKeywords = (((this.keywords!= null)&&(!this.keywords.isEmpty()))?this.getKeywords():null);
            List<Keyword> rightKeywords;
            rightKeywords = (((that.keywords!= null)&&(!that.keywords.isEmpty()))?that.getKeywords():null);
            if ((this.keywords!= null)&&(!this.keywords.isEmpty())) {
                if ((that.keywords!= null)&&(!that.keywords.isEmpty())) {
                    if (!leftKeywords.equals(rightKeywords)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.keywords!= null)&&(!that.keywords.isEmpty())) {
                    return false;
                }
            }
        }
        {
            String leftOwner;
            leftOwner = this.getOwner();
            String rightOwner;
            rightOwner = that.getOwner();
            if (this.owner!= null) {
                if (that.owner!= null) {
                    if (!leftOwner.equals(rightOwner)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.owner!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            List<Keyword> theKeywords;
            theKeywords = (((this.keywords!= null)&&(!this.keywords.isEmpty()))?this.getKeywords():null);
            if ((this.keywords!= null)&&(!this.keywords.isEmpty())) {
                currentHashCode += theKeywords.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theOwner;
            theOwner = this.getOwner();
            if (this.owner!= null) {
                currentHashCode += theOwner.hashCode();
            }
        }
        return currentHashCode;
    }

}
