//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Country" minOccurs="0"/&gt;
 *         &lt;element ref="{}MedlineTA"/&gt;
 *         &lt;element ref="{}NlmUniqueID" minOccurs="0"/&gt;
 *         &lt;element ref="{}ISSNLinking" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "country",
    "medlineTA",
    "nlmUniqueID",
    "issnLinking"
})
@XmlRootElement(name = "MedlineJournalInfo")
public class MedlineJournalInfo implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Country")
    protected String country;
    @XmlElement(name = "MedlineTA", required = true)
    protected String medlineTA;
    @XmlElement(name = "NlmUniqueID")
    protected String nlmUniqueID;
    @XmlElement(name = "ISSNLinking")
    protected String issnLinking;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the medlineTA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedlineTA() {
        return medlineTA;
    }

    /**
     * Sets the value of the medlineTA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedlineTA(String value) {
        this.medlineTA = value;
    }

    /**
     * Gets the value of the nlmUniqueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNlmUniqueID() {
        return nlmUniqueID;
    }

    /**
     * Sets the value of the nlmUniqueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNlmUniqueID(String value) {
        this.nlmUniqueID = value;
    }

    /**
     * Gets the value of the issnLinking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSNLinking() {
        return issnLinking;
    }

    /**
     * Sets the value of the issnLinking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSNLinking(String value) {
        this.issnLinking = value;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final MedlineJournalInfo that = ((MedlineJournalInfo) object);
        {
            String leftCountry;
            leftCountry = this.getCountry();
            String rightCountry;
            rightCountry = that.getCountry();
            if (this.country!= null) {
                if (that.country!= null) {
                    if (!leftCountry.equals(rightCountry)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.country!= null) {
                    return false;
                }
            }
        }
        {
            String leftMedlineTA;
            leftMedlineTA = this.getMedlineTA();
            String rightMedlineTA;
            rightMedlineTA = that.getMedlineTA();
            if (this.medlineTA!= null) {
                if (that.medlineTA!= null) {
                    if (!leftMedlineTA.equals(rightMedlineTA)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.medlineTA!= null) {
                    return false;
                }
            }
        }
        {
            String leftNlmUniqueID;
            leftNlmUniqueID = this.getNlmUniqueID();
            String rightNlmUniqueID;
            rightNlmUniqueID = that.getNlmUniqueID();
            if (this.nlmUniqueID!= null) {
                if (that.nlmUniqueID!= null) {
                    if (!leftNlmUniqueID.equals(rightNlmUniqueID)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.nlmUniqueID!= null) {
                    return false;
                }
            }
        }
        {
            String leftISSNLinking;
            leftISSNLinking = this.getISSNLinking();
            String rightISSNLinking;
            rightISSNLinking = that.getISSNLinking();
            if (this.issnLinking!= null) {
                if (that.issnLinking!= null) {
                    if (!leftISSNLinking.equals(rightISSNLinking)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.issnLinking!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            String theCountry;
            theCountry = this.getCountry();
            if (this.country!= null) {
                currentHashCode += theCountry.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theMedlineTA;
            theMedlineTA = this.getMedlineTA();
            if (this.medlineTA!= null) {
                currentHashCode += theMedlineTA.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theNlmUniqueID;
            theNlmUniqueID = this.getNlmUniqueID();
            if (this.nlmUniqueID!= null) {
                currentHashCode += theNlmUniqueID.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theISSNLinking;
            theISSNLinking = this.getISSNLinking();
            if (this.issnLinking!= null) {
                currentHashCode += theISSNLinking.hashCode();
            }
        }
        return currentHashCode;
    }

}
