//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}DescriptorName"/&gt;
 *         &lt;element ref="{}QualifierName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "descriptorName",
    "qualifierNames"
})
@XmlRootElement(name = "MeshHeading")
public class MeshHeading implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "DescriptorName", required = true)
    protected DescriptorName descriptorName;
    @XmlElement(name = "QualifierName")
    protected List<QualifierName> qualifierNames;

    /**
     * Gets the value of the descriptorName property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptorName }
     *     
     */
    public DescriptorName getDescriptorName() {
        return descriptorName;
    }

    /**
     * Sets the value of the descriptorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptorName }
     *     
     */
    public void setDescriptorName(DescriptorName value) {
        this.descriptorName = value;
    }

    /**
     * Gets the value of the qualifierNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualifierNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualifierNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualifierName }
     * 
     * 
     */
    public List<QualifierName> getQualifierNames() {
        if (qualifierNames == null) {
            qualifierNames = new ArrayList<QualifierName>();
        }
        return this.qualifierNames;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final MeshHeading that = ((MeshHeading) object);
        {
            DescriptorName leftDescriptorName;
            leftDescriptorName = this.getDescriptorName();
            DescriptorName rightDescriptorName;
            rightDescriptorName = that.getDescriptorName();
            if (this.descriptorName!= null) {
                if (that.descriptorName!= null) {
                    if (!leftDescriptorName.equals(rightDescriptorName)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.descriptorName!= null) {
                    return false;
                }
            }
        }
        {
            List<QualifierName> leftQualifierNames;
            leftQualifierNames = (((this.qualifierNames!= null)&&(!this.qualifierNames.isEmpty()))?this.getQualifierNames():null);
            List<QualifierName> rightQualifierNames;
            rightQualifierNames = (((that.qualifierNames!= null)&&(!that.qualifierNames.isEmpty()))?that.getQualifierNames():null);
            if ((this.qualifierNames!= null)&&(!this.qualifierNames.isEmpty())) {
                if ((that.qualifierNames!= null)&&(!that.qualifierNames.isEmpty())) {
                    if (!leftQualifierNames.equals(rightQualifierNames)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.qualifierNames!= null)&&(!that.qualifierNames.isEmpty())) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            DescriptorName theDescriptorName;
            theDescriptorName = this.getDescriptorName();
            if (this.descriptorName!= null) {
                currentHashCode += theDescriptorName.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            List<QualifierName> theQualifierNames;
            theQualifierNames = (((this.qualifierNames!= null)&&(!this.qualifierNames.isEmpty()))?this.getQualifierNames():null);
            if ((this.qualifierNames!= null)&&(!this.qualifierNames.isEmpty())) {
                currentHashCode += theQualifierNames.hashCode();
            }
        }
        return currentHashCode;
    }

}
