//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{}StartPage"/&gt;
 *           &lt;element ref="{}EndPage" minOccurs="0"/&gt;
 *           &lt;element ref="{}MedlinePgn" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element ref="{}MedlinePgn"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startPage",
    "endPage",
    "medlinePgn"
})
@XmlRootElement(name = "Pagination")
public class Pagination implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "StartPage")
    protected String startPage;
    @XmlElement(name = "EndPage")
    protected String endPage;
    @XmlElement(name = "MedlinePgn")
    protected String medlinePgn;

    /**
     * Gets the value of the startPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPage() {
        return startPage;
    }

    /**
     * Sets the value of the startPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPage(String value) {
        this.startPage = value;
    }

    /**
     * Gets the value of the endPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndPage() {
        return endPage;
    }

    /**
     * Sets the value of the endPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPage(String value) {
        this.endPage = value;
    }

    /**
     * Gets the value of the medlinePgn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedlinePgn() {
        return medlinePgn;
    }

    /**
     * Sets the value of the medlinePgn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedlinePgn(String value) {
        this.medlinePgn = value;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Pagination that = ((Pagination) object);
        {
            String leftStartPage;
            leftStartPage = this.getStartPage();
            String rightStartPage;
            rightStartPage = that.getStartPage();
            if (this.startPage!= null) {
                if (that.startPage!= null) {
                    if (!leftStartPage.equals(rightStartPage)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.startPage!= null) {
                    return false;
                }
            }
        }
        {
            String leftEndPage;
            leftEndPage = this.getEndPage();
            String rightEndPage;
            rightEndPage = that.getEndPage();
            if (this.endPage!= null) {
                if (that.endPage!= null) {
                    if (!leftEndPage.equals(rightEndPage)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.endPage!= null) {
                    return false;
                }
            }
        }
        {
            String leftMedlinePgn;
            leftMedlinePgn = this.getMedlinePgn();
            String rightMedlinePgn;
            rightMedlinePgn = that.getMedlinePgn();
            if (this.medlinePgn!= null) {
                if (that.medlinePgn!= null) {
                    if (!leftMedlinePgn.equals(rightMedlinePgn)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.medlinePgn!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            String theStartPage;
            theStartPage = this.getStartPage();
            if (this.startPage!= null) {
                currentHashCode += theStartPage.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theEndPage;
            theEndPage = this.getEndPage();
            if (this.endPage!= null) {
                currentHashCode += theEndPage.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theMedlinePgn;
            theMedlinePgn = this.getMedlinePgn();
            if (this.medlinePgn!= null) {
                currentHashCode += theMedlinePgn.hashCode();
            }
        }
        return currentHashCode;
    }

}
