//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:14:59 AM CDT 
//


package edu.utdallas.hltri.data.medline.jaxb.struct;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}History" minOccurs="0"/&gt;
 *         &lt;element ref="{}PublicationStatus"/&gt;
 *         &lt;element ref="{}ArticleIdList"/&gt;
 *         &lt;element ref="{}ObjectList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "history",
    "publicationStatus",
    "articleIdList",
    "objectList"
})
@XmlRootElement(name = "PubmedData")
public class PubmedData implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "History")
    protected History history;
    @XmlElement(name = "PublicationStatus", required = true)
    protected String publicationStatus;
    @XmlElement(name = "ArticleIdList", required = true)
    protected ArticleIdList articleIdList;
    @XmlElement(name = "ObjectList")
    protected ObjectList objectList;

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link History }
     *     
     */
    public History getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link History }
     *     
     */
    public void setHistory(History value) {
        this.history = value;
    }

    /**
     * Gets the value of the publicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationStatus() {
        return publicationStatus;
    }

    /**
     * Sets the value of the publicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationStatus(String value) {
        this.publicationStatus = value;
    }

    /**
     * Gets the value of the articleIdList property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleIdList }
     *     
     */
    public ArticleIdList getArticleIdList() {
        return articleIdList;
    }

    /**
     * Sets the value of the articleIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleIdList }
     *     
     */
    public void setArticleIdList(ArticleIdList value) {
        this.articleIdList = value;
    }

    /**
     * Gets the value of the objectList property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectList }
     *     
     */
    public ObjectList getObjectList() {
        return objectList;
    }

    /**
     * Sets the value of the objectList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectList }
     *     
     */
    public void setObjectList(ObjectList value) {
        this.objectList = value;
    }

    public boolean equals(java.lang.Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PubmedData that = ((PubmedData) object);
        {
            History leftHistory;
            leftHistory = this.getHistory();
            History rightHistory;
            rightHistory = that.getHistory();
            if (this.history!= null) {
                if (that.history!= null) {
                    if (!leftHistory.equals(rightHistory)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.history!= null) {
                    return false;
                }
            }
        }
        {
            String leftPublicationStatus;
            leftPublicationStatus = this.getPublicationStatus();
            String rightPublicationStatus;
            rightPublicationStatus = that.getPublicationStatus();
            if (this.publicationStatus!= null) {
                if (that.publicationStatus!= null) {
                    if (!leftPublicationStatus.equals(rightPublicationStatus)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.publicationStatus!= null) {
                    return false;
                }
            }
        }
        {
            ArticleIdList leftArticleIdList;
            leftArticleIdList = this.getArticleIdList();
            ArticleIdList rightArticleIdList;
            rightArticleIdList = that.getArticleIdList();
            if (this.articleIdList!= null) {
                if (that.articleIdList!= null) {
                    if (!leftArticleIdList.equals(rightArticleIdList)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.articleIdList!= null) {
                    return false;
                }
            }
        }
        {
            ObjectList leftObjectList;
            leftObjectList = this.getObjectList();
            ObjectList rightObjectList;
            rightObjectList = that.getObjectList();
            if (this.objectList!= null) {
                if (that.objectList!= null) {
                    if (!leftObjectList.equals(rightObjectList)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.objectList!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            History theHistory;
            theHistory = this.getHistory();
            if (this.history!= null) {
                currentHashCode += theHistory.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String thePublicationStatus;
            thePublicationStatus = this.getPublicationStatus();
            if (this.publicationStatus!= null) {
                currentHashCode += thePublicationStatus.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ArticleIdList theArticleIdList;
            theArticleIdList = this.getArticleIdList();
            if (this.articleIdList!= null) {
                currentHashCode += theArticleIdList.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ObjectList theObjectList;
            theObjectList = this.getObjectList();
            if (this.objectList!= null) {
                currentHashCode += theObjectList.hashCode();
            }
        }
        return currentHashCode;
    }

}
